<div class="outer">
 <div class="inner bg-light lter">
<div class="col-lg-12">
      <h1>bootstrap-admin-template</h1>
      <p>Metis is a simple yet powerful free Bootstrap admin dashboard template that you can feel free to use for any app, service, software or anything else. Feel free to share and fork it.</p>
      <p>This template currently is slighly outdated but withing few weeks we are going to make a major overhaul making ot the best free admin template you have seen on Github or elsehwere on the web.</p>
      <ul>
      </ul>
      <h2>Download</h2>
      <ul>
      <li>Bootstrap 2.3.2 <a href="https://github.com/puikinsh/Bootstrap-Admin-Template/archive/v1.2.zip">v1.2</a>
      ready for use</li>
      <li>Bootstrap 3.3.7 <a href="https://puikinsh.com/puikinsh/Bootstrap-Admin-Template/archive/master.zip">v2.3.2</a>
      ready <code>public</code> folder your use</li>
      </ul>
      
      <h2>Credits</h2>

      <h2>About Authors</h2>
      <ul>
      <li><a href="https://colorlib.com/">Colorlib</a> - Colorlib is the most popular source for free WordPress themes and HTML templates.</li>
      <li><a href="https://twitter.com/AigarsSilkalns">Aigars Silkalns</a> - Aigars maintains this project and is also the idea author behind Colorlib and everythiwn you will find on that website.</li>
      </ul>
      <h2>License</h2>
      <p>Copyright (c) 2016 Aigars Silkalns & Colorlib</p>
      <p>Released under the MIT license. This free Bootstrap admin template is distributed as as it with no support. You can feeel free to use it, share it, tweakit it, workin it, sell it or do whatver you want as long as you keep the original license in plce.</p>
      <hr>
      <p><em>This file was generated by <a href="https://github.com/verbose/verb">verb</a>, v0.9.0, on July 31, 2016.</em></p>
    </div>
  </div>
   <!-- /.inner -->
</div>
                    <!-- /.outer -->